### ISSUE TITLE
USB3.0 can't change to usb2.0

### ISSUE THREAD

**Issue by SLboat** [gzenux/asuswrt-rtn18u#11]
hi, thank you great work.i found if we change usb to usb2.0,it will reboot,but after,it still show usb3.0,so is it normal?
![SLboat-Mac-Screen2019-10-1320 13 59](https://user-images.githubusercontent.com/4231376/66715445-07cb1c00-edf6-11e9-8ec4-448bea16dc2b.jpg)

**Comment by gzenux** [comment]
這是我合併華碩官方source code時所造成的bug，我會在下一版釋出時解決。

**Comment by SLboat** [comment]
太棒了!


From SLboat

**Comment by SLboat** [comment]
亲爱的台湾同胞,汇报下使用一个月的感受,最近使用中对你的改版实在太满意了,装了entware还有一系列工具,装了个小U盘,尽管单核的处理器,但实在足够了.
朋友用的AC88U,花了700多人民币购置的,确实多了很多你说的闭源功能,而且官方固件内核也进步很多,比如N18U的官方固件是只有telnet的,但是88U是有ssh选项的,尽管提供的选项不如梅林多.也可以想象这个项目的未来是暗淡的.

有一个奇怪的现象,我想再此一提: 如果开着管理界面,然后重启路由器,此时如果路由器丢失了,网页的管理页面会导致很高的CPU占用率,拿我的Mac来说,会让CPU发热,风扇开始大转.

所以我很奇怪,为什么等待一个没有结果的回馈会让路由器管理页面如此的卡顿?
很抱歉,这是一个粗略的观察.我觉得大概可以这样复现: 开着路由器管理页面,登录后留在比如首页[网络地图],然后让路由器脱离网络,一些时间之后,这个网页就像脱缰的野马一样开始狂吃CPU,也许是某种查阅协议得不到结果而更努力的尝试了?

From SLboat

**Comment by SLboat** [comment]
是的,很奇怪的BUG哈哈.


From SLboat

**Comment by Eldenroot** [comment]
Please in English :)

**Comment by gzenux** [comment]
Regarding to the USB mode issue, it's caused by my bad merged code from the latest GPL release. This bug will be fixed by the next release.(This issue will be closed when I release the beta)

A further more discussion at few hours ago was another issue and actually it's not related to current issue, please don't be confused.

**Comment by gzenux** [comment]
Fixed in beta release.
