### ISSUE TITLE
384.13beta2, ssh端口冲突提示

### ISSUE THREAD

**Issue by SLboat** [gzenux/asuswrt-rtn18u#15]
在系统设置里开启SSH后,保存,再次关闭一次ssh设置,保存,再次试图打开,会提示这个端口不能用,必须修改一下
![image](https://user-images.githubusercontent.com/4231376/70139239-fbb05c00-16cc-11ea-8a00-9e68945477b0.png)

备注: 更新的时候是直接升级的,没有清除nvram更新

**Comment by SLboat** [comment]
wps按钮似乎也不起到作用.
![image](https://user-images.githubusercontent.com/4231376/70142269-cbb88700-16d3-11ea-9e20-8fdfbba38547.png)

**Comment by gzenux** [comment]
It's a bug introduced by new asuswrt but fixed by merlin in upstream commit 89ebb9a624.
This upstream bugfix was committed after the beta2 release so it will be merged by next release.

**Comment by gzenux** [comment]
The WPS button function works fine in my side.
What are the nvram values in 'btn_ez_mode' and 'btn_wps_gpio'?

**Comment by SLboat** [comment]
![image](https://user-images.githubusercontent.com/4231376/70152868-e9441b80-16e8-11ea-8763-18693a8410b3.png)
再加一个: 不知道这里是不是我个别的问题,扫描磁盘后,看不到任何日志,记忆里旧版本是有的.

**Comment by SLboat** [comment]
> The WPS button function works fine in my side.
> What are the nvram values in 'btn_ez_mode' and 'btn_wps_gpio'?

```bash
# nvram get btn_ez_mode
1
# nvram get btn_wps_gpio
4107
```

**Comment by SLboat** [comment]
> It's a bug introduced by new asuswrt but fixed by merlin in upstream commit 89ebb9a624.
> This upstream bugfix was committed after the beta2 release so it will be merged by next release.

thank you quick replay:)

**Comment by gzenux** [comment]
I'm not sure what exact issues you faced since the watchdog uses the same gpio to periodically detect WPS button status.
If all three WPS functions are not working, I think it might be the failure to detect the gpio status or watchdog deaded.
Is it working on some previous versions(or the specific version)?

Regarding to the issue of the usb disk scan report, I can reproduce it. I'll try to take a look for the root cause.
I think it should be better to open a new ticket to keep track of this issue in order to avoid all issues mixing together. Thanks~

**Comment by SLboat** [comment]
很抱歉,我今天又试了,长按若干秒可以关闭开启!是我理解错了,以为只是短按一下.

新版本很棒!


From SLboat

**Comment by SLboat** [comment]
好主意,我会打开一个新的issue来跟踪:)

我注意到你的提交代码关于增加日志选项的功能里,只增加了短短几行代码,就做到了,真神奇.这个华硕的asp应该不是微软的asp,只是做了一些预处理吧.

其实很不明白,日志都迁移到了rsyslog了,为何梅林不提供一个选项不写jffs日志,只写内存的,尤其像我这种开了远程日志的.又或者,非要写可以写入外置存储.

也就相当于一个选项:
长久保存日志 = 闪存|外置存储|禁止


From SLboat

**Comment by gzenux** [comment]
The rsyslog feature is introduced in recent asuswrt but NOT enabled by merlin (please refer to RT-N18U changelog for more info.).

The persistent log feature is not supported by RT-N18U but the log backing up/restoring to/from flash(/jffs) is support in an automatic way only.
The log is backed up before the router normal rebooting and is restored after the router booted.

I add the log protocol switch option is only for fixing compatibility issue due to lacking asuswrt support in the current stage.
Regarding to persistent log switch option, I don't intend to implement it currently. Thanks~

**Comment by SLboat** [comment]
明白了,完全理解不增加额外的功能,能保持同步就已经最棒了.

只是印象里不知道听谁说路由器的闪存次数读写有限,可能是梅林的Wiki,不过这两个小文件确实应该没有什么"杀伤力",但是想来entware放在外置媒体,而系统动态甚至配置文件都在内存里,却也觉得有点唏嘘.

这真是个有趣的工作,感谢你的努力!


From SLboat

**Comment by SLboat** [comment]
beta3已经没有这个问题!感谢!
