### ISSUE TITLE
The Download Master not show in USB applications menu

### ISSUE THREAD

**Issue by andris155** [gzenux/asuswrt-rtn18u#3]
After update to 384.9 Download Master in USB applications not show, and slow loading this page.
I tested without external HDD - Download Master show. But if connected external HDD - Download Master not show.
And Download Master works perfectly with link on the 384.9 version.
![Annotation 2019-04-18 152732](https://user-images.githubusercontent.com/8324198/56364297-7f751100-61ee-11e9-9369-627a4aade7ee.png)
![Annotation 2019-04-18 152804](https://user-images.githubusercontent.com/8324198/56364331-9287e100-61ee-11e9-81f9-944b839b2a31.png)

**Comment by gzenux** [comment]
This issue is caused by Asus's codebase (our 384.9 merge GPL 384_45149), see the discussion in SNBforums:
https://www.snbforums.com/threads/asus-download-master-crippled-in-384-9-384-10-asuswrt-merlin-fw.55724/

There is a bug fix for this webui/httpd issue from Asuswrt-Merlin and the next version (384.9_2) will merge this bug fix.

You can manually downgrade to the previous stable version by following URL: (Please note GPL 384_45149 was merged starting 384.9-beta1)
https://gzenux.github.io/asuswrt-rtn18u/RT-N18U/RT-N18U_384.8_3.trx

If you can build the image from the source code, the following two commits which are from upstream ([Asuswrt-Merlin](https://github.com/RMerl/asuswrt-merlin.ng)) can fix this issue (mainly the first one):
[cc7e0d278b](https://github.com/RMerl/asuswrt-merlin.ng/commit/cc7e0d278b356fc79279f0d524c5acc09e9aabe2) httpd: fix potential buffer overrun in alloc_string() (backport from 384_45708)
[77ba03b6e7](https://github.com/RMerl/asuswrt-merlin.ng/commit/77ba03b6e7e8ae1448c9717e8450b3fc05a65d95) httpd: replace homemade alloc_string() with strdup() that does the exact same thing

**Comment by andris155** [comment]
I wait next version. Thanks.

**Comment by Aldione** [comment]
mmm, i was thinking to update this firmware, but i preffer to wait to next version, because i want to use download master...

With the official asus update, i dont know why my download master turn off automatic and i need to remove the usb and restart the router and put on the usb

**Comment by Aldione** [comment]
> If you can build the image from the source code, the following two commits which are from upstream ([Asuswrt-Merlin](https://github.com/RMerl/asuswrt-merlin.ng)) can fix this issue (mainly the first one):
> [cc7e0d278b](https://github.com/RMerl/asuswrt-merlin.ng/commit/cc7e0d278b356fc79279f0d524c5acc09e9aabe2) httpd: fix potential buffer overrun in alloc_string() (backport from 384_45708)
> [77ba03b6e7](https://github.com/RMerl/asuswrt-merlin.ng/commit/77ba03b6e7e8ae1448c9717e8450b3fc05a65d95) httpd: replace homemade alloc_string() with strdup() that does the exact same thing

Why you dont fix it and upload?

**Comment by gzenux** [comment]
[384.9_1](https://gzenux.github.io/asuswrt-rtn18u/RT-N18U/RT-N18U_384.9_1.trx) is available now. I'll close this issue if there are no problems regarding it.

**Comment by andris155** [comment]
384_1 fixed this. Thanks!
