### ISSUE TITLE
After flashing this firmware, main features work fine, but cannot login.

### ISSUE THREAD

**Issue by zybersup** [gzenux/asuswrt-rtn18u#30]
We moved from the stock firmware to this one version 384.16. After uploading the firmware and then waited until it finished the reboot, we found it worked fine except that we cannot login with admin/admin or the previous username/password. We also tried username/password pairs we could imagine with no success. We also could not get through VPN.

Is there any quick solution or we should do the factory reset as you suggest on your home page? We would not like to set all the settings again because we customized it so many places. And with this strange problem, we now afraid that we may not be able to login with admin/admin after the factory reset or not.

Thank you for making these new functionalities possible for the RT-N18U.

**Comment by gzenux** [comment]
The default login information is the same with stock firmware.

If you have backed up settings from the stock firmware, then you might try to upload this backup file on 384.16 after the router restored to default by pressing the reset button.

Please note that the settings backed up from stock firmware might still cause some features not working properly (I don't try this way yet) on 384.16 since the nvram setting might be not compatiable with stock firmware.

**Comment by zybersup** [comment]
Thank you very much for your fast response.

I tried all logins we can imagine but could not accomplish it. It could be because of the change of password encryption in version 384.5 (as you noted in Changelog-RTN18U.txt).

I see that you also note in the installation instruction that we have to "Restore to default by hardware button" but everything worked well after flashing the firmware so I do not want to do the factory reset.

Finally we do the factory reset and use the default login and then restore the backed up settings. Everything done!

Thanks again for making this firmware available.
