### ISSUE TITLE
Wifi Range

### ISSUE THREAD

**Issue by manirhossen** [gzenux/asuswrt-rtn18u#37]
In this latest version wifi range not good enough. I dont know what is the problen but if possiable please increase wifi range. When i use HGG firmware this wifi range like double than This firmware. 

Thank You ❤️❤️❤️

**Comment by gzenux** [comment]
It's the same with issue #9.
This should be not an issue since the Tx power is limited by the region which the product is sold to meet the local regulatory requirements.

It's no way to change the region and the power range by current 384.18 release.
The 384.19-beta1 release lets you have a chance to change the region and the power range for testing purposes, but you still need to take care your local regulatory requirements. Use this feature at your own risk if you really want to change the Tx power in a non-factory way.
