### ISSUE TITLE
Samba with password login not work 384.11

### ISSUE THREAD

**Issue by andris155** [gzenux/asuswrt-rtn18u#4]
If I connect with correct name and password connect not work.
The older 384.10 version works perfectly with password connect.
If I enabled Allow guest login works perfectly with new version.

**Comment by andris155** [comment]
<img width="307" alt="Annotation 2019-07-08 201042" src="https://user-images.githubusercontent.com/8324198/60832577-82174f00-a1bc-11e9-9d80-f287f2dc7cae.png">
And not work with Windows 10. Only work MiXplorer with Android.

**Comment by gzenux** [comment]
I find the difference /etc/smb.conf between two versions might be the root cause.
The error dialogues does not show on my windows 10 but I get login failed in 384.11

Could you try to update /etc/smb.conf and then restart samba service on 384.11?

Step 1. login with SSH and then edit /etc/smb.conf with nano or vi by appending the following settings in [global] section:
```
socket options = IPTOS_LOWDELAY TCP_NODELAY SO_KEEPALIVE
enable core files = no
deadtime = 30
load printers = no
printable = no
max protocol = SMB2
smb encrypt = disabled
min receivefile size = 16384
passdb backend = smbpasswd
smb passwd file = /etc/samba/smbpasswd
```

Step 2. restart samba service by using the following commands:
`killall smbd nmbd`
`nmbd -D -s /etc/smb.conf`
`/usr/sbin/smbd -D -s /etc/smb.conf`

Step 3. finally try to connect to samba service with Windows 10.

Hope above solution can solve your problem.

**Comment by andris155** [comment]
Works perfectly.
Thanks!!

**Comment by gzenux** [comment]
It's good to hear your problem solved.
Please note that the configuration is not permanent, it will go back original settings after router reboot.
I'll prepare the next release to fix it. Thanks.
