### ISSUE TITLE
GUI is slow and unresponsive

### ISSUE THREAD

**Issue by Eldenroot** [gzenux/asuswrt-rtn18u#8]
I flashed your fw on my RT-N18u. I used Tomato fw before.

Everything is fine except one thing - sometimes the GUI is really slow and unresponsive. I have tried to reboot device but without any success. It happens only sometimes, tried in Google Chrome/Edge chromium/Firefox.

I do not how to reproduce. Any recommendation?

**Comment by Eldenroot** [comment]
OK, I am not alone - it is a bug with .12? 

https://github.com/RMerl/asuswrt-merlin.ng/issues/326

better to wait for Asus to fix this.

@gzenux

**Comment by maxbraketorque** [comment]
If you are connecting to the router interface via https, then the slow, sometimes unresponsive behavior, is a known issue as Merlin says a few posts after the one that you referenced.  If you connect via http, the interface should be very responsive.

**Comment by Eldenroot** [comment]
I use only HTTP, anyway the GUI is slow (according to the post above I am not the only one)

**Comment by andris155** [comment]
I use 384.11_1 and my GUI is very fast.

**Comment by Eldenroot** [comment]
Enable QoS adaptive and try, it happens only with QoS senabled

**Comment by maxbraketorque** [comment]
ok.  I have not tried with QoS enabled, but there are many people running QoS in Merlin 384.12.  Have you tried clearing your browser cache as others have suggested?  If that doesn't fix it, then it may be an issue specific only some routers.

**Comment by gzenux** [comment]
I can reproduce this issue with QoS enabled. According to Merlin's issue discussion, someone mentioned that Merlin 384.11_2 has no such problem.

It's very likely caused by commit f67ebf59ef and dbd4abf8f7, which solved CVE-2019-11477, CVE-2019-11478 and CVE-2019-11479.
I can't figure out why these commits conflict with QoS feature and I'm not sure whether should revert these commits since they are security patches.

I would like to wait for Merlin to solve this issue. If you really need to enable QoS, my current suggestions are:

1. Use previous release [384.10](https://gzenux.github.io/asuswrt-rtn18u/RT-N18U/RT-N18U_384.10_0.trx) (384.11 has a samba known issue)

or

2. Apply the following workaround to disable TCP SACK (needs to apply setting every boot)
    `# echo 0 > /proc/sys/net/ipv4/tcp_sack`

Please note that the GUI response is slower than `#1` but a little faster than current state.(tested on my router)

**Comment by Eldenroot** [comment]
@gzenux - thank you for your input.

I disabled QoS for now (I have optic fiber connection 100/100 Mbps so I think it is not necessary to use QoS for now).

Let @RMerl solve this issue or wait for official Asus fix. In my opinion you should NOT revert these CVE commits, better to have slow GUI than security holes in our devices.

**Comment by maxbraketorque** [comment]
100/100 mbps are pretty reasonable up/down speeds.  Unless you are continually using a good fraction of that bandwidth for file transfer, or are a really serious gamer, I don't think QoS is needed.  I use BT heavily for anime, and I do my file transfer rate limits within the BT software rather than by QoS in the router.

**Comment by gzenux** [comment]
I think I find the solution. Tested on my router.

Reference: [https://lkml.org/lkml/2019/6/26/163](https://lkml.org/lkml/2019/6/26/163)

**Comment by Eldenroot** [comment]
Great!

**Comment by themiron** [comment]
thanks, applied

**Comment by maxbraketorque** [comment]
Nice job.  Do you know if this fix been identified for Merlin's FWs as well?

**Comment by gzenux** [comment]
@Eldenroot 384.11_2 now available and it has contained this bugfix.
I'll close this issue if there is no more problem with it.

**Comment by Eldenroot** [comment]
I updated, feel free to update it. I will open a new ticket if anything :) thx!
