### ISSUE TITLE
TX power Low signal - slow speed

### ISSUE THREAD

**Issue by komaramnt** [gzenux/asuswrt-rtn18u#9]
First thank you for your hard work ! Sorry for my bad English.
I was testing 384.11_1 and then 384.11_2 but have problem with coverage.
Before I was on HGG fork firmware and the range of the same spot was better and speeds was faster. On 384.11_2 I login with SSH and check wl txpow it was 31 dbm wich is the maximum.
Reset the router, I try differen settings but not getting near the results on HGG firmware.
I think the problem is in me but cant find it :) So I go back to HGG and the speed at the same spot and coverege was back to normal (+50%). I wish to use your firmware so please check that for me.
Thanks in advance!

**Comment by Eldenroot** [comment]
Url link for that firmware + version?

**Comment by komaramnt** [comment]
> Url link for that firmware + version?

Dont want to make trouble to gzenux if it is not problem I will post a link but you can find it yoreself by googling hgg n18u firmware

**Comment by Eldenroot** [comment]
The signal is better because this firmware gas a modified power for wifi part. Anyway it is not allowed to use that, it is not legal. Your device will have higher temperatures and will die sooner.

**Comment by gzenux** [comment]
Just as Eldenroot says, HGG firmware modified the tx power.
I simply follow original AsusWRT without any tx power modification.

Actually the tx power tuning functionality has become closed source by Asus since 3.0.0.4.378.8041 (i.e. the final source avaiable version is 3.0.0.4.378.4850).
If you really want to use more high tx power other than original AsusWRT, you need to revert the related code(release/src/router/rc/sysdeps/init-broadcom.c) from GPL source 3.0.0.4.378.4850.
The detail way is replacing set_wltxpower() to prevent calling this function from prebuilt binary (release/src/router/rc/prebuild/RT-N18U/tcode_brcm.o), and then re-build the image from source code.

I think this is not issue since original AsusWRT should be the same behavior.
Currently I have no plan to let tx power adjustment be customizable but you can patch code and build image by your own from this project. Thanks~

**Comment by komaramnt** [comment]
Thank you !!! 
This is all I need :) so your firmware is perfect and I'm glad you explain it :)
Sorry for openin the case !
And again thank you for hard work !
